name: PR CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ${{ matrix.system.os }}
    strategy:
      matrix:
        include:
        - system:
            os:
            - self-hosted
            - macOS
            - ARM64
            target: aarch64-apple-darwin
          architecture: arm64
          rust_version: stable-aarch64-apple-darwin
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          cache: true
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
      - name: format
        run: |
          make format
          if [ -z "$(git status --untracked-files=no --porcelain)" ]; then
            echo "All files formatted"
          else
            echo "Running format is required"
            exit 1
          fi
      - name: test
        run: make test
      - name: build
        run: make lengine
