name: PR CI

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.system.os }}
    strategy:
      matrix:
        include:
        - system:
            os:
            - self-hosted
            - macOS
            - ARM64
            target: aarch64-apple-darwin
          architecture: arm64
          rust_version: stable-aarch64-apple-darwin
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
